version: '3'

services:
  api:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./api:/usr/src/api
    # tty: true
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
    
