version: '3'

volumes:
  app_data: {}
services:
  api:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./api:/usr/src/api
      - app_data:/var/log
    # tty: true
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  promtail:
    image: grafana/promtail:1.6.1
    volumes:
      - app_data:/var/log
      - ./promtail:/etc/promtail
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail-local-config.yaml

  loki:
    image: grafana/loki:1.6.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:8.3.0
    ports:
      - "3000:3000"

  localstack:
    image: localstack/localstack:0.14.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
